'use strict';

const axios = require('axios');
const crypto = require('crypto');
const logger = require('../utils/logger');

const client = axios.create({
  baseURL: `${process.env.WHATSAPP_API_BASE}/${process.env.WHATSAPP_PHONE_NUMBER_ID}`,
  timeout: 8000,
  headers: {
    Authorization: `Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`,
    'Content-Type': 'application/json',
  },
});

/**
 * Verifies the X-Hub-Signature-256 header Meta sends on every webhook
 * delivery, using a timing-safe comparison. Rejects the request outright
 * if this fails — never process a payload we can't authenticate as
 * genuinely from Meta's infrastructure.
 */
function verifyWebhookSignature(rawBody, signatureHeader) {
  if (!signatureHeader || !signatureHeader.startsWith('sha256=')) return false;
  const expected = crypto
    .createHmac('sha256', process.env.WHATSAPP_APP_SECRET)
    .update(rawBody)
    .digest('hex');
  const provided = signatureHeader.replace('sha256=', '');

  const expectedBuf = Buffer.from(expected, 'hex');
  const providedBuf = Buffer.from(provided, 'hex');
  if (expectedBuf.length !== providedBuf.length) return false;
  return crypto.timingSafeEqual(expectedBuf, providedBuf);
}

async function sendTextMessage(toWhatsappNumber, body) {
  return safeSend({
    messaging_product: 'whatsapp',
    to: toWhatsappNumber,
    type: 'text',
    text: { preview_url: true, body },
  });
}

/**
 * Sends the generated receipt card image inline into the chat stream by
 * URL (the safe, expiring, unguessable link produced by receiptService).
 */
async function sendReceiptImage(toWhatsappNumber, imageUrl, caption) {
  return safeSend({
    messaging_product: 'whatsapp',
    to: toWhatsappNumber,
    type: 'image',
    image: { link: imageUrl, caption },
  });
}

/**
 * Sends the Paystack checkout link inline as a plain text message with
 * a preview so WhatsApp renders a rich link card.
 */
async function sendPaymentLink(toWhatsappNumber, paymentUrl, amountLabel) {
  return safeSend({
    messaging_product: 'whatsapp',
    to: toWhatsappNumber,
    type: 'text',
    text: {
      preview_url: true,
      body: `🚀 *Kika Premium Upgrade*\n\nAmount: ${amountLabel}\nComplete your payment securely here:\n${paymentUrl}\n\nYour premium window activates automatically the moment payment clears.`,
    },
  });
}

/**
 * Presents pricing tiers as tappable WhatsApp reply buttons in response to
 * the generic UPGRADE keyword, so the merchant picks a plan instead of
 * guessing which keyword to type. WhatsApp allows a maximum of 3 reply
 * buttons per message and a 20-character title limit per button.
 */
async function sendPlanSelectionButtons(toWhatsappNumber, buttons) {
  return safeSend({
    messaging_product: 'whatsapp',
    to: toWhatsappNumber,
    type: 'interactive',
    interactive: {
      type: 'button',
      body: { text: '\ud83d\ude80 *Upgrade Kika*\n\nChoose a plan to continue:' },
      action: {
        buttons: buttons.slice(0, 3).map((b) => ({
          type: 'reply',
          reply: { id: b.id, title: b.title.slice(0, 20) },
        })),
      },
    },
  });
}

/**
 * Sends the Monthly Digest as an image with a tappable "View Full Report"
 * call-to-action button linking out to the hosted full report page —
 * matches the card + link pattern shown in the product's WhatsApp UI.
 */
async function sendMonthlyDigestCard(toWhatsappNumber, { imageUrl, bodyText, reportUrl }) {
  return safeSend({
    messaging_product: 'whatsapp',
    to: toWhatsappNumber,
    type: 'interactive',
    interactive: {
      type: 'cta_url',
      header: { type: 'image', image: { link: imageUrl } },
      body: { text: bodyText },
      footer: { text: 'Generated by Kika AI' },
      action: {
        name: 'cta_url',
        parameters: { display_text: 'View Full Report', url: reportUrl },
      },
    },
  });
}

async function safeSend(payload) {
  try {
    const res = await client.post('/messages', payload);
    return res.data;
  } catch (err) {
    logger.error(
      { err: err.response?.data || err.message, to: payload.to },
      'WhatsApp send failed'
    );
    throw err;
  }
}

module.exports = {
  verifyWebhookSignature,
  sendTextMessage,
  sendReceiptImage,
  sendPaymentLink,
  sendPlanSelectionButtons,
  sendMonthlyDigestCard,
};
