-- ---------------------------------------------------------------------------
-- Kika ledger schema
-- Zero-signup model: a merchant "account" is created implicitly the first
-- time a WhatsApp number messages the bot. Phone number (E.164) is the
-- natural key.
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Generic trigger function to keep updated_at fresh — defined first since
-- several tables below attach a trigger to it.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Subscription tiers — the single source of truth for pricing, currency,
-- billing interval, and marketing feature copy. Every other table that
-- needs to know "which plan" now references this table by id (FK) rather
-- than re-declaring its own CHECK-constrained string enum, so a price
-- change or a new tier is a data update, not a schema/code change.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subscription_tiers (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(40)  NOT NULL UNIQUE,        -- 'Free', 'Standard', 'Premium'
    description     TEXT,                                 -- short marketing blurb for the pricing page
    price           NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (price >= 0), -- major currency unit (e.g. 5000.00, not kobo), monthly billing
    price_yearly    NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (price_yearly >= 0), -- annual billing, priced at 10x the monthly rate (2 months free) to reward commitment
    currency        VARCHAR(3)   NOT NULL DEFAULT 'NGN' CHECK (currency ~ '^[A-Z]{3}$'),
    "interval"      VARCHAR(10)  NOT NULL DEFAULT 'monthly' CHECK ("interval" IN ('monthly', 'yearly')),
    feature_list    JSONB        NOT NULL DEFAULT '[]',   -- ordered array of perk strings shown on the pricing page
    is_active       BOOLEAN      NOT NULL DEFAULT true,   -- false hides a retired tier from new customers
    display_order   INTEGER      NOT NULL DEFAULT 0,      -- ascending sort position on the pricing page
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (display_order)
);

CREATE INDEX IF NOT EXISTS idx_subscription_tiers_active_order
    ON subscription_tiers (is_active, display_order);

-- Defensive backfill, run BEFORE the seed INSERT below references this
-- column: on a fresh install CREATE TABLE above already has it, so this
-- is a no-op; on a database migrated before price_yearly existed, this
-- is what makes the INSERT's column list valid at all. Without this,
-- re-running this file against such a database would fail the INSERT
-- and — since migrate.js executes this entire file as one implicit
-- transaction — abort the WHOLE migration, not just this one statement.
ALTER TABLE subscription_tiers ADD COLUMN IF NOT EXISTS price_yearly NUMERIC(12, 2) NOT NULL DEFAULT 0;

-- Seed the three tiers with fixed, predictable ids (1/2/3) so application
-- code can default new merchants to id 1 (Free) without a lookup.
-- ON CONFLICT keeps this script safe to re-run against an existing DB.
INSERT INTO subscription_tiers (id, name, description, price, price_yearly, currency, "interval", feature_list, is_active, display_order)
VALUES
  (1, 'Free', 'Get started with zero-signup ledger tracking on WhatsApp.',
     0.00, 0.00, 'NGN', 'monthly',
     '["Unlimited sales, expense & debt logging via chat","Auto-generated receipt cards","Live BALANCE snapshot on demand","Daily Sunset Report on request"]'::jsonb,
     true, 1),
  (2, 'Standard', 'For growing merchants who want daily visibility and repeat-customer tracking.',
     5000.00, 50000.00, 'NGN', 'monthly',
     '["Everything in Free","Automatic Daily Sunset Report every evening","Monthly Insights summary","Smart Customer Loyalty Flags (5th-purchase pings)","Priority WhatsApp support"]'::jsonb,
     true, 2),
  (3, 'Premium', 'The full Kika AI experience: rich analytics and automated monthly reporting.',
     10000.00, 100000.00, 'NGN', 'monthly',
     '["Everything in Standard","Monthly Digest card with AI-generated insights","Full Monthly Report (weekly revenue, debtor breakdown, top products)","Smart Customer Loyalty Flags","Priority WhatsApp support"]'::jsonb,
     true, 3)
ON CONFLICT (id) DO NOTHING;

-- Keep the identity sequence ahead of the manually-seeded ids above, so
-- the next tier created through the app gets id 4, not a collision with 1-3.
SELECT setval(pg_get_serial_sequence('subscription_tiers', 'id'), 3, true);

DROP TRIGGER IF EXISTS trg_subscription_tiers_updated_at ON subscription_tiers;
CREATE TRIGGER trg_subscription_tiers_updated_at
    BEFORE UPDATE ON subscription_tiers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS merchants (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    whatsapp_number     VARCHAR(20)  NOT NULL UNIQUE,   -- E.164, e.g. +2348012345678
    display_name        VARCHAR(120),                   -- legacy/unused free-text field, kept for compatibility; superseded by whatsapp_display_name + merchant_name below
    business_name       VARCHAR(160),
    whatsapp_display_name VARCHAR(160),                 -- the contact's WhatsApp profile name, captured automatically from `contacts[0].profile.name` on every webhook delivery — not something the merchant told us, just Meta's own metadata
    merchant_name        VARCHAR(120),                  -- the merchant's OWN name, only ever set when they actually introduce themselves ("I'm Samuel") or answer a direct name prompt — deliberately separate from whatsapp_display_name and business_name
    business_type        VARCHAR(160),                  -- the merchant's own free-text answer to "what type of business is it?", asked immediately after business_name during onboarding
    business_category    VARCHAR(60),                   -- Kika's classification of business_type into one fixed category (e.g. "Retail", "Wholesale") — see categorizationService.js
    email                VARCHAR(255),                   -- only ever set when the merchant explicitly gives it in reply to the email-collection prompt (see engagementService.js) — never inferred or required
    subscription_tier_id INTEGER NOT NULL DEFAULT 1 REFERENCES subscription_tiers(id), -- 1 = Free
    subscription_expires_at TIMESTAMPTZ,                -- NULL while on the Free tier
    onboarding_state    VARCHAR(24)  NOT NULL DEFAULT 'PENDING_CONSENT'
                         CHECK (onboarding_state IN (
                            'PENDING_CONSENT', 'CONSENT_DECLINED', 'AWAITING_BUSINESS_NAME', 'AWAITING_BUSINESS_TYPE',
                            'NEW', 'ACTIVE', 'STANDARD_ACTIVE', 'PREMIUM_ACTIVE'
                         )),
    consent_at          TIMESTAMPTZ,                     -- when the merchant tapped "I AGREE" — compliance record
    consent_prompt_count SMALLINT NOT NULL DEFAULT 0,     -- how many times we've (re)sent the consent prompt without an accept; capped at 3 before we stop nudging
    closing_hour_local  SMALLINT NOT NULL DEFAULT 19 CHECK (closing_hour_local BETWEEN 0 AND 23), -- Africa/Lagos hour the Business Sunset ping fires
    logo_file_path       TEXT,                            -- uploaded business logo, embedded into receipts once set
    awaiting_logo_until TIMESTAMPTZ,                      -- short window after a fresh premium purchase where the next image is treated as a logo upload, not a transaction scan
    default_currency    VARCHAR(3)   NOT NULL DEFAULT 'NGN',
    -- NPS survey state — see engagementService.js. nps_awaiting_stage tracks
    -- a specific in-progress survey conversation (SCORE -> REASON), kept
    -- separate from onboarding_state since it's a periodic interrupt on an
    -- already-ACTIVE merchant, not a gate. nps_last_prompted_at both records
    -- when we last asked (for the "track satisfaction over time" cadence)
    -- and gates re-prompting too soon.
    nps_awaiting_stage  VARCHAR(10) CHECK (nps_awaiting_stage IN ('SCORE', 'REASON')),
    nps_last_prompted_at TIMESTAMPTZ,
    nps_pending_trigger_reason VARCHAR(20) CHECK (nps_pending_trigger_reason IN ('ONE_MONTH', 'MILESTONE')), -- which condition fired the CURRENTLY in-progress survey, carried from the prompt through to the eventual score reply — see engagementService.js
    -- Email-collection state — same shape as the NPS state above, for the
    -- "want me to email you reports/tips?" milestone nudge.
    email_collection_awaiting_stage VARCHAR(12) CHECK (email_collection_awaiting_stage IN ('OPT_IN', 'EMAIL')),
    email_collection_last_prompted_at TIMESTAMPTZ,
    -- Receipt confirmation batching — see engagementService.js /
    -- worker.js. A transaction is recorded immediately as always, but
    -- the receipt image is no longer auto-sent; ledger_entries.
    -- receipt_decision_pending (added below) tracks which entries are
    -- still awaiting a yes/no, and this flag is set true the moment
    -- Kika actually ASKS ("type DONE when you want your receipt(s)" ->
    -- merchant sends DONE) so the merchant's next message is read as
    -- the answer rather than a new transaction or command.
    receipt_decision_awaiting BOOLEAN NOT NULL DEFAULT false,
    -- Multi-turn invoice creation ("new invoice for Adaeze" -> item
    -- lines -> DONE -> preview -> yes/no). NEVER sent to the customer —
    -- see receiptService.js's generateInvoiceCard and worker.js's
    -- invoice-flow handling: the finished invoice + payment link are
    -- handed to the MERCHANT to forward themselves.
    invoice_awaiting_stage VARCHAR(10) CHECK (invoice_awaiting_stage IN ('ITEMS', 'CONFIRM')),
    invoice_customer_name VARCHAR(160),
    invoice_pending_items JSONB NOT NULL DEFAULT '[]',
    next_invoice_number INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_merchants_whatsapp_number ON merchants (whatsapp_number);
CREATE INDEX IF NOT EXISTS idx_merchants_subscription_tier ON merchants (subscription_tier_id);
CREATE INDEX IF NOT EXISTS idx_merchants_closing_hour ON merchants (closing_hour_local);

-- Every sale / expense / debt entry a merchant records via chat.
-- `total_kobo` is the full value of the transaction; `paid_kobo` is what was
-- actually handed over at the time; `balance_kobo` is what's still owed
-- (0 for a fully-paid CREDIT/DEBIT). This three-way split mirrors how
-- merchants actually talk: "she pay 15k remain 12k" on a 27k sale.
CREATE TABLE IF NOT EXISTS ledger_entries (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    entry_type          VARCHAR(20) NOT NULL CHECK (entry_type IN ('CREDIT', 'DEBIT', 'DEBT', 'DEBT_SETTLEMENT')),
    counterparty_name   VARCHAR(160),                    -- customer/supplier name, optional
    counterparty_phone  VARCHAR(20),                     -- optional E.164 customer number, for loyalty tracking
    description         TEXT NOT NULL,
    items               JSONB NOT NULL DEFAULT '[]',     -- [{name, quantity, unit}], best-effort extraction
    total_kobo          BIGINT NOT NULL CHECK (total_kobo >= 0),
    paid_kobo           BIGINT NOT NULL DEFAULT 0 CHECK (paid_kobo >= 0),
    balance_kobo        BIGINT NOT NULL DEFAULT 0 CHECK (balance_kobo >= 0),
    balance_after_kobo  BIGINT,                          -- customer's rolling debt balance snapshot immediately after this entry (DEBT/DEBT_SETTLEMENT only) — computed under row lock, see customer_balances
    currency            VARCHAR(3) NOT NULL DEFAULT 'NGN',
    is_settled          BOOLEAN NOT NULL DEFAULT false,  -- true once balance_kobo hits 0
    is_voided           BOOLEAN NOT NULL DEFAULT false,  -- true once undone via the UNDO command
    voided_at           TIMESTAMPTZ,
    raw_message         TEXT,                            -- original WhatsApp text, for audit
    receipt_id          UUID,                             -- set once a receipt card is generated
    receipt_decision_pending BOOLEAN NOT NULL DEFAULT true, -- true until the merchant has said yes/no to "want a receipt for this?" (see worker.js's DONE-triggered confirmation flow); flipped false either way once resolved
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Defensive backfill, run BEFORE the indexes below reference this column
-- — see the identical comment on subscription_tiers.price_yearly above
-- for why this matters (a database migrated before this column existed
-- would otherwise fail the very next CREATE INDEX statement and, since
-- migrate.js runs this whole file as one implicit transaction, abort
-- the entire migration).
ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS receipt_decision_pending BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS idx_ledger_entries_merchant_created
    ON ledger_entries (merchant_id, created_at DESC) WHERE is_voided = false;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_outstanding_debt
    ON ledger_entries (merchant_id, is_settled) WHERE balance_kobo > 0 AND is_voided = false;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_items_gin
    ON ledger_entries USING GIN (items);
CREATE INDEX IF NOT EXISTS idx_ledger_entries_counterparty_phone
    ON ledger_entries (merchant_id, counterparty_phone) WHERE counterparty_phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_receipt_decision_pending
    ON ledger_entries (merchant_id, created_at) WHERE receipt_decision_pending = true AND is_voided = false;

-- ---------------------------------------------------------------------------
-- Customer balances — the single authoritative "account" row per
-- (merchant, customer) holding their current rolling debt balance.
--
-- This exists specifically to eliminate a race condition: ledger_entries
-- rows are independent inserts, so two "sales on credit" to the SAME
-- customer arriving within seconds of each other (two concurrent worker
-- jobs) have nothing to serialize against one another on if the rolling
-- total is only ever computed by SUMming ledger_entries at read time.
-- Every debt-affecting write (a new DEBT, or a DEBT_SETTLEMENT payment)
-- must go through queries.lockCustomerBalance() first, which:
--   1. INSERTs the row if it doesn't exist yet (ON CONFLICT DO NOTHING —
--      itself race-safe: if two transactions both try to create a brand
--      new customer's first row concurrently, only one insert wins)
--   2. SELECTs it back with FOR UPDATE inside the caller's transaction
-- A second concurrent transaction touching the same customer blocks on
-- that FOR UPDATE until the first COMMITs, then reads the up-to-date
-- balance — guaranteeing no lost updates regardless of how many sales
-- land for the same customer at the same instant.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_balances (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id          UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    counterparty_name    VARCHAR(160) NOT NULL,
    rolling_balance_kobo BIGINT NOT NULL DEFAULT 0 CHECK (rolling_balance_kobo >= 0),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, counterparty_name)
);

CREATE INDEX IF NOT EXISTS idx_customer_balances_merchant
    ON customer_balances (merchant_id);

DROP TRIGGER IF EXISTS trg_customer_balances_updated_at ON customer_balances;
CREATE TRIGGER trg_customer_balances_updated_at
    BEFORE UPDATE ON customer_balances
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Products / inventory — opt-in stock tracking. A product only exists
-- here once a merchant explicitly registers it via "ADD STOCK: name, qty".
-- Sales that mention a matching item name (case-insensitive) decrement
-- current_stock; crossing below low_stock_threshold fires the Low Stock
-- Alert appended to that sale's receipt.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id          UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    name                 VARCHAR(160) NOT NULL,
    unit                 VARCHAR(40),
    current_stock        NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    low_stock_threshold  NUMERIC(12, 2) NOT NULL DEFAULT 5,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness ("Rice" and "rice" are the same product)
-- via an expression index rather than a plain UNIQUE constraint.
CREATE UNIQUE INDEX IF NOT EXISTS idx_products_merchant_name_ci
    ON products (merchant_id, lower(name));

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Data exports — CSV ledger exports generated for premium merchants,
-- served the same way as receipts (unguessable token, expiring), and
-- swept by the same disk-cleanup job once expired.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS data_exports (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id     UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    file_path       TEXT NOT NULL,
    public_token    VARCHAR(64) NOT NULL UNIQUE,
    period_label    VARCHAR(40),
    expires_at      TIMESTAMPTZ NOT NULL,
    file_deleted_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_data_exports_public_token ON data_exports (public_token);
CREATE INDEX IF NOT EXISTS idx_data_exports_cleanup_sweep
    ON data_exports (expires_at) WHERE file_deleted_at IS NULL;

-- Tracks which merchants have already received a given day's Sunset
-- Report or a given month's Insights report, so a retried/duplicated
-- scheduler tick can never send the same report twice.
CREATE TABLE IF NOT EXISTS report_dispatch_log (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    report_type         VARCHAR(24) NOT NULL CHECK (report_type IN ('DAILY_SUNSET', 'MONTHLY_INSIGHTS', 'MONTHLY_DIGEST', 'FRIDAY_AMNESTY_PROMPT')),
    period_key          VARCHAR(10) NOT NULL,             -- 'YYYY-MM-DD' or 'YYYY-MM'
    sent_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, report_type, period_key)
);

-- Generated receipt card assets (rendered PNGs served over a signed URL).
CREATE TABLE IF NOT EXISTS receipts (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    ledger_entry_id      UUID REFERENCES ledger_entries(id) ON DELETE SET NULL,
    file_path           TEXT NOT NULL,
    public_token        VARCHAR(64) NOT NULL UNIQUE,   -- random, unguessable path segment
    expires_at          TIMESTAMPTZ NOT NULL,
    file_deleted_at     TIMESTAMPTZ,                    -- set once the on-disk file has been pruned (after expires_at); NULL while the file still exists
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_receipts_public_token ON receipts (public_token);
CREATE INDEX IF NOT EXISTS idx_receipts_cleanup_sweep
    ON receipts (expires_at) WHERE file_deleted_at IS NULL;

-- Generated Monthly Digest card images (the compact WhatsApp visual with
-- Money Inflow / Outstanding Credit / Trade Days / Top Debtor).
CREATE TABLE IF NOT EXISTS digest_cards (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    period_key          VARCHAR(10) NOT NULL,            -- 'YYYY-MM'
    file_path           TEXT NOT NULL,
    public_token        VARCHAR(64) NOT NULL UNIQUE,
    expires_at          TIMESTAMPTZ NOT NULL,
    file_deleted_at     TIMESTAMPTZ,                      -- set once the on-disk file has been pruned (after expires_at); NULL while the file still exists
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, period_key)
);

CREATE INDEX IF NOT EXISTS idx_digest_cards_public_token ON digest_cards (public_token);
CREATE INDEX IF NOT EXISTS idx_digest_cards_cleanup_sweep
    ON digest_cards (expires_at) WHERE file_deleted_at IS NULL;

-- The full "View Full Report" web page a merchant lands on after tapping
-- through from their Monthly Digest — stored as a data snapshot (not
-- recomputed live) so the report stays consistent even as new ledger
-- entries come in after the digest was sent.
CREATE TABLE IF NOT EXISTS monthly_reports (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    period_key          VARCHAR(10) NOT NULL,            -- 'YYYY-MM'
    report_data         JSONB NOT NULL,                  -- full computed snapshot (totals, weekly revenue, debts, top products, AI insight)
    public_token        VARCHAR(64) NOT NULL UNIQUE,
    expires_at          TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, period_key)
);

CREATE INDEX IF NOT EXISTS idx_monthly_reports_public_token ON monthly_reports (public_token);

-- Loyalty tracking: one row per (merchant, customer phone). Purchases
-- increment purchase_count; every 5th purchase ("milestone") triggers a
-- ping to the customer, gated to Standard/Premium merchants only.
CREATE TABLE IF NOT EXISTS customer_loyalty (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    counterparty_phone  VARCHAR(20) NOT NULL,
    counterparty_name   VARCHAR(160),
    purchase_count      INTEGER NOT NULL DEFAULT 0,
    last_milestone_notified INTEGER NOT NULL DEFAULT 0,  -- last purchase_count a milestone ping was sent at
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, counterparty_phone)
);

-- Net Promoter Score survey responses — one row per completed survey (a
-- merchant can be asked again after the cooldown in engagementService.js,
-- so this is intentionally NOT unique per merchant; every response is its
-- own row, which is what "track satisfaction over time" needs). `score` is
-- saved the moment the merchant answers the 0-10 question; `reason` is
-- filled in by a follow-up UPDATE once they answer the "why" question, and
-- stays NULL if they never do (score alone is still useful).
CREATE TABLE IF NOT EXISTS nps_responses (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    score               SMALLINT NOT NULL CHECK (score BETWEEN 0 AND 10),
    reason              TEXT,
    trigger_reason      VARCHAR(20) NOT NULL DEFAULT 'MILESTONE' CHECK (trigger_reason IN ('ONE_MONTH', 'MILESTONE')), -- which condition fired this particular prompt — see engagementService.js
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_nps_responses_merchant_id ON nps_responses (merchant_id, created_at DESC);

-- Paystack payment attempts for tier upgrades.
CREATE TABLE IF NOT EXISTS payment_transactions (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    paystack_reference  VARCHAR(100) NOT NULL UNIQUE,
    subscription_tier_id INTEGER NOT NULL REFERENCES subscription_tiers(id),
    billing_interval    VARCHAR(10) NOT NULL DEFAULT 'monthly' CHECK (billing_interval IN ('monthly', 'yearly')),
    amount_kobo         BIGINT NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'ABANDONED')),
    authorization_url   TEXT,
    verified_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_reference
    ON payment_transactions (paystack_reference);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_merchant
    ON payment_transactions (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_tier
    ON payment_transactions (subscription_tier_id);

-- ---------------------------------------------------------------------------
-- Access control — blacklist/whitelist by WhatsApp number, and a
-- label-based bot pause so a human agent can take over a conversation
-- without the bot auto-replying underneath them.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS access_control_list (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number    VARCHAR(20) NOT NULL UNIQUE,          -- E.164
    list_type       VARCHAR(10) NOT NULL CHECK (list_type IN ('BLACKLIST', 'WHITELIST')),
    reason          TEXT,
    created_by      VARCHAR(120),                          -- admin identifier who added the rule
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_access_control_phone ON access_control_list (phone_number);
CREATE INDEX IF NOT EXISTS idx_access_control_type ON access_control_list (list_type);

-- Labels applied to a merchant's conversation (e.g. by a support agent in
-- a CRM/handoff tool). While an unresolved "skip" label is active
-- (matched against SKIP_BOT_LABELS), the bot logs the inbound message but
-- does not auto-reply, leaving the human agent in control.
CREATE TABLE IF NOT EXISTS conversation_labels (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id     UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    label           VARCHAR(60) NOT NULL,
    applied_by      VARCHAR(120),
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at      TIMESTAMPTZ                             -- NULL while still active
);

CREATE INDEX IF NOT EXISTS idx_conversation_labels_active
    ON conversation_labels (merchant_id) WHERE removed_at IS NULL;

-- ---------------------------------------------------------------------------
-- Payment links — every digital invoice/checkout link sent inside a
-- WhatsApp chat, across any gateway. `short_url` is the compact link
-- actually texted to the customer (see linkShortenerService); `gateway`
-- and `gateway_reference` tie it back to the underlying Paystack/Stripe/
-- Flutterwave transaction for reconciliation.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_links (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    gateway             VARCHAR(20) NOT NULL CHECK (gateway IN ('paystack', 'stripe', 'flutterwave')),
    gateway_reference   VARCHAR(150) NOT NULL,             -- the gateway's own transaction reference
    full_url            TEXT NOT NULL,                      -- the long authorization/checkout URL from the gateway
    short_url           VARCHAR(255) NOT NULL UNIQUE,       -- compact link sent in the WhatsApp text
    short_code          VARCHAR(20) NOT NULL UNIQUE,        -- the path segment of short_url, for fast lookup
    amount_kobo         BIGINT NOT NULL CHECK (amount_kobo >= 0),
    currency            VARCHAR(3) NOT NULL DEFAULT 'NGN',
    customer_phone      VARCHAR(20),
    customer_name       VARCHAR(160),
    description         TEXT,
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'EXPIRED', 'CANCELLED')),
    ledger_entry_id     UUID REFERENCES ledger_entries(id) ON DELETE SET NULL, -- set once payment auto-records a CREDIT
    expires_at          TIMESTAMPTZ NOT NULL,                -- when the link becomes invalid
    paid_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payment_links_short_code ON payment_links (short_code);
CREATE INDEX IF NOT EXISTS idx_payment_links_merchant ON payment_links (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_links_gateway_reference ON payment_links (gateway, gateway_reference);
CREATE INDEX IF NOT EXISTS idx_payment_links_status ON payment_links (status) WHERE status = 'PENDING';

DROP TRIGGER IF EXISTS trg_payment_links_updated_at ON payment_links;
CREATE TRIGGER trg_payment_links_updated_at
    BEFORE UPDATE ON payment_links
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Payment gateway activity log — every outbound call and inbound webhook
-- to/from any payment gateway (Paystack today), for reconciliation and
-- support debugging. Distinct from payment_transactions/payment_links,
-- which hold current state; this table is an append-only trail of every
-- attempt, retry, and webhook delivery.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_gateway_logs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID REFERENCES merchants(id) ON DELETE SET NULL,
    payment_link_id     UUID REFERENCES payment_links(id) ON DELETE SET NULL,
    gateway             VARCHAR(20) NOT NULL,
    event_type          VARCHAR(50) NOT NULL,   -- e.g. 'transaction.initialize', 'charge.success', 'verify.transaction'
    reference           VARCHAR(150),
    http_status         INTEGER,
    request_payload     JSONB,
    response_payload    JSONB,
    is_success          BOOLEAN NOT NULL,
    error_message       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payment_gateway_logs_reference ON payment_gateway_logs (reference);
CREATE INDEX IF NOT EXISTS idx_payment_gateway_logs_merchant ON payment_gateway_logs (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_gateway_logs_event ON payment_gateway_logs (gateway, event_type);

-- ---------------------------------------------------------------------------
-- Ledger disputes & adjustments — customer or merchant complaints about
-- an incorrect ledger balance, and how they were resolved.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ledger_disputes (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    ledger_entry_id     UUID REFERENCES ledger_entries(id) ON DELETE SET NULL,
    raised_by           VARCHAR(20) NOT NULL DEFAULT 'MERCHANT' CHECK (raised_by IN ('MERCHANT', 'CUSTOMER', 'SYSTEM')),
    customer_phone      VARCHAR(20),
    reason              TEXT NOT NULL,
    disputed_amount_kobo BIGINT,
    adjustment_amount_kobo BIGINT,          -- signed delta actually applied, once resolved
    status              VARCHAR(16) NOT NULL DEFAULT 'OPEN'
                         CHECK (status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED')),
    resolution_notes    TEXT,
    resolved_by         VARCHAR(120),
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_disputes_merchant ON ledger_disputes (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_disputes_status ON ledger_disputes (status) WHERE status IN ('OPEN', 'UNDER_REVIEW');

DROP TRIGGER IF EXISTS trg_ledger_disputes_updated_at ON ledger_disputes;
CREATE TRIGGER trg_ledger_disputes_updated_at
    BEFORE UPDATE ON ledger_disputes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Application/API audit log — every inbound HTTP request the service
-- handles (endpoint, method, status, actor), for security review and
-- operational debugging. Written by the auditLogger middleware on every
-- request; also used for explicit business-event audit entries (e.g.
-- "merchant.blacklisted", "payment_link.created") via auditLogService.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id     UUID REFERENCES merchants(id) ON DELETE SET NULL,
    actor_type      VARCHAR(20) NOT NULL DEFAULT 'SYSTEM' CHECK (actor_type IN ('MERCHANT', 'SYSTEM', 'ADMIN', 'WEBHOOK')),
    actor_id        VARCHAR(120),                -- phone number, admin username, or 'system'
    action          VARCHAR(100) NOT NULL,       -- e.g. 'ledger_entry.create', 'payment_link.create', 'merchant.blacklist'
    endpoint        VARCHAR(150),
    http_method     VARCHAR(10),
    status_code     INTEGER,
    is_success      BOOLEAN NOT NULL DEFAULT true,
    request_id      VARCHAR(64),
    ip_address      VARCHAR(45),
    metadata        JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_merchant ON audit_logs (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at DESC);

-- Immutability: audit_logs may only ever be INSERTed into. This is
-- enforced here, at the database level, rather than just "the app code
-- never calls UPDATE/DELETE" (true today, but that's a promise, not a
-- guarantee) — a trigger means even a future bug, a direct psql session,
-- or an admin script can't silently rewrite or erase history. The only
-- way around it is a superuser explicitly disabling the trigger first,
-- which is itself the point: mutation becomes a deliberate, visible act,
-- never an accident.
CREATE OR REPLACE FUNCTION prevent_audit_log_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is immutable — % is not permitted (row id=%)', TG_OP, COALESCE(OLD.id, NEW.id);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_audit_logs_immutable_update ON audit_logs;
CREATE TRIGGER trg_audit_logs_immutable_update
    BEFORE UPDATE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();

DROP TRIGGER IF EXISTS trg_audit_logs_immutable_delete ON audit_logs;
CREATE TRIGGER trg_audit_logs_immutable_delete
    BEFORE DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();

-- Attach the updated_at trigger to the remaining tables that need it.
DROP TRIGGER IF EXISTS trg_merchants_updated_at ON merchants;
CREATE TRIGGER trg_merchants_updated_at
    BEFORE UPDATE ON merchants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_customer_loyalty_updated_at ON customer_loyalty;
CREATE TRIGGER trg_customer_loyalty_updated_at
    BEFORE UPDATE ON customer_loyalty
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Migration: merchant identity (WhatsApp display name vs. self-introduced
-- name), business type/category classification, and WhatsApp message
-- traceability (dedup, audit, reply-context resolution) on ledger entries.
--
-- Written as ADD COLUMN IF NOT EXISTS / idempotent DDL throughout so
-- re-running this whole schema.sql (migrate.js's only migration
-- mechanism — see that file) against an already-migrated database is a
-- no-op, exactly like every other table above.
--
-- whatsapp_display_name, merchant_name, business_type, and
-- business_category now live INLINE in the CREATE TABLE merchants
-- statement above, positioned right after business_name — that's what
-- controls physical column order for a FRESH database. The ADD COLUMN
-- statements below are kept purely as a backward-compatible safety net
-- for a database that was already migrated before this reordering (they
-- no-op there, since the columns already exist): Postgres has no
-- non-destructive way to reorder existing columns, so an
-- already-migrated database will keep them at the end. That's a
-- cosmetic-only difference (SELECT * column order) with no functional
-- impact — every query in this codebase reads columns by name, never by
-- position.
-- ---------------------------------------------------------------------------

-- whatsapp_display_name: the contact's profile name as reported by
-- WhatsApp itself (`contacts[0].profile.name` on every webhook delivery)
-- — captured automatically the moment they first message us, no prompt
-- needed. merchant_name: the name the merchant actually gave US when
-- introducing themselves in conversation ("I'm Samuel", or a direct
-- answer to a name prompt) — deliberately a SEPARATE column, since a
-- WhatsApp display name is often a shop name, an emoji, or a nickname a
-- merchant wouldn't want Kika calling them by, and shouldn't silently
-- overwrite a name they explicitly gave us.
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS whatsapp_display_name VARCHAR(160);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS merchant_name VARCHAR(120);

-- business_type: the merchant's own free-text answer to "what type of
-- business is it?" (e.g. "Provision Store"), asked immediately after
-- business_name during onboarding. business_category: Kika's own
-- classification of that free text into one fixed marketing/analytics
-- category (e.g. "Wholesale") — see categorizationService.js. Kept as
-- two columns because business_type is what the merchant actually said
-- (shown back to them, useful verbatim) while business_category is a
-- normalized value the rest of the product (segment-specific tips,
-- future analytics, support tooling) can group and filter on.
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS business_type VARCHAR(160);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS business_category VARCHAR(60);


-- New onboarding step: business type is collected immediately after
-- business name, before a merchant reaches ACTIVE. Postgres CHECK
-- constraints can't be altered in place, so drop and recreate by the
-- name Postgres auto-assigned it (<table>_<column>_check).
ALTER TABLE merchants DROP CONSTRAINT IF EXISTS merchants_onboarding_state_check;
ALTER TABLE merchants ADD CONSTRAINT merchants_onboarding_state_check
    CHECK (onboarding_state IN (
        'PENDING_CONSENT', 'CONSENT_DECLINED', 'AWAITING_BUSINESS_NAME', 'AWAITING_BUSINESS_TYPE',
        'NEW', 'ACTIVE', 'STANDARD_ACTIVE', 'PREMIUM_ACTIVE'
    ));

-- WhatsApp message traceability on every ledger entry:
--   whatsapp_message_id          — the inbound wamid of the merchant
--                                   message that created this entry.
--                                   Redis's idempotency lock (see
--                                   idempotencyService.js) already blocks
--                                   double-processing within its 48h TTL;
--                                   this column is the permanent,
--                                   queryable record for auditing and
--                                   traceability after that TTL expires.
--   reply_to_whatsapp_message_id — populated from the inbound webhook's
--                                   `context.id` when the merchant's
--                                   message was itself a reply to an
--                                   earlier WhatsApp message.
--   outbound_whatsapp_message_id — the wamid of KIKA'S OWN reply/receipt
--                                   about this entry. When a later
--                                   inbound message's `context.id`
--                                   matches this column, Kika knows
--                                   exactly which entry a bare reply like
--                                   "he paid" refers to — see
--                                   ledgerParser.parseReplyMessage and
--                                   queries.getLedgerEntryByOutboundMessageId.
ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS whatsapp_message_id VARCHAR(128);
ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS reply_to_whatsapp_message_id VARCHAR(128);
ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS outbound_whatsapp_message_id VARCHAR(128);

-- expense_category: Kika's classification of a DEBIT entry into a fixed
-- expense category (e.g. "Inventory & Stock", "Transport & Logistics")
-- — see categorizationService.js. NULL for non-DEBIT entries.
ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS expense_category VARCHAR(60);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ledger_entries_whatsapp_message_id
    ON ledger_entries (whatsapp_message_id) WHERE whatsapp_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_outbound_whatsapp_message_id
    ON ledger_entries (outbound_whatsapp_message_id) WHERE outbound_whatsapp_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_expense_category
    ON ledger_entries (merchant_id, expense_category) WHERE expense_category IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Migration: NPS survey (nps_responses table + merchants state columns) and
-- opt-in email collection (merchants.email + state columns). Both are
-- deterministic conversation flows handled entirely in worker.js /
-- engagementService.js — no AI involved — see those files.
--
-- email, nps_awaiting_stage, nps_last_prompted_at,
-- email_collection_awaiting_stage, and email_collection_last_prompted_at
-- now live INLINE in the CREATE TABLE merchants statement above (email
-- positioned right before subscription_tier_id, as requested). The ADD
-- COLUMN statements below are the same backward-compatible safety net
-- pattern used elsewhere in this file — a no-op on a fresh database, and
-- what actually adds these columns (at the end, physically) on a database
-- migrated before this change. See the earlier migration block's comment
-- for why physical column order can't be changed non-destructively.
-- ---------------------------------------------------------------------------
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS nps_awaiting_stage VARCHAR(10);
ALTER TABLE merchants DROP CONSTRAINT IF EXISTS merchants_nps_awaiting_stage_check;
ALTER TABLE merchants ADD CONSTRAINT merchants_nps_awaiting_stage_check
    CHECK (nps_awaiting_stage IN ('SCORE', 'REASON'));
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS nps_last_prompted_at TIMESTAMPTZ;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS nps_pending_trigger_reason VARCHAR(20);
ALTER TABLE merchants DROP CONSTRAINT IF EXISTS merchants_nps_pending_trigger_reason_check;
ALTER TABLE merchants ADD CONSTRAINT merchants_nps_pending_trigger_reason_check
    CHECK (nps_pending_trigger_reason IN ('ONE_MONTH', 'MILESTONE'));
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS email_collection_awaiting_stage VARCHAR(12);
ALTER TABLE merchants DROP CONSTRAINT IF EXISTS merchants_email_collection_awaiting_stage_check;
ALTER TABLE merchants ADD CONSTRAINT merchants_email_collection_awaiting_stage_check
    CHECK (email_collection_awaiting_stage IN ('OPT_IN', 'EMAIL'));
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS email_collection_last_prompted_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS nps_responses (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    score               SMALLINT NOT NULL CHECK (score BETWEEN 0 AND 10),
    reason              TEXT,
    trigger_reason      VARCHAR(20) NOT NULL DEFAULT 'MILESTONE' CHECK (trigger_reason IN ('ONE_MONTH', 'MILESTONE')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_nps_responses_merchant_id ON nps_responses (merchant_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Migration: yearly billing. price_yearly now lives inline on
-- subscription_tiers above (10x monthly = 2 months free); billing_interval
-- lives inline on payment_transactions above. Same backward-compatible
-- ADD COLUMN pattern for a database migrated before this change.
-- ---------------------------------------------------------------------------
ALTER TABLE subscription_tiers ADD COLUMN IF NOT EXISTS price_yearly NUMERIC(12, 2) NOT NULL DEFAULT 0;
UPDATE subscription_tiers SET price_yearly = price * 10 WHERE price_yearly = 0 AND price > 0;

ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS billing_interval VARCHAR(10) NOT NULL DEFAULT 'monthly';
ALTER TABLE payment_transactions DROP CONSTRAINT IF EXISTS payment_transactions_billing_interval_check;
ALTER TABLE payment_transactions ADD CONSTRAINT payment_transactions_billing_interval_check
    CHECK (billing_interval IN ('monthly', 'yearly'));

-- ---------------------------------------------------------------------------
-- Migration: DONE-triggered receipt confirmation batching, and the
-- multi-turn invoice creation flow. Both are deterministic conversation
-- flows in worker.js — no AI involved.
-- ---------------------------------------------------------------------------
ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS receipt_decision_pending BOOLEAN NOT NULL DEFAULT true;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_receipt_decision_pending
    ON ledger_entries (merchant_id, created_at) WHERE receipt_decision_pending = true AND is_voided = false;

ALTER TABLE merchants ADD COLUMN IF NOT EXISTS receipt_decision_awaiting BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS invoice_awaiting_stage VARCHAR(10);
ALTER TABLE merchants DROP CONSTRAINT IF EXISTS merchants_invoice_awaiting_stage_check;
ALTER TABLE merchants ADD CONSTRAINT merchants_invoice_awaiting_stage_check
    CHECK (invoice_awaiting_stage IN ('ITEMS', 'CONFIRM'));
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS invoice_customer_name VARCHAR(160);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS invoice_pending_items JSONB NOT NULL DEFAULT '[]';
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS next_invoice_number INTEGER NOT NULL DEFAULT 1;
