-- ---------------------------------------------------------------------------
-- Kika ledger schema
-- Zero-signup model: a merchant "account" is created implicitly the first
-- time a WhatsApp number messages the bot. Phone number (E.164) is the
-- natural key.
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Generic trigger function to keep updated_at fresh — defined first since
-- several tables below attach a trigger to it.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Subscription tiers — the single source of truth for pricing, currency,
-- billing interval, and marketing feature copy. Every other table that
-- needs to know "which plan" now references this table by id (FK) rather
-- than re-declaring its own CHECK-constrained string enum, so a price
-- change or a new tier is a data update, not a schema/code change.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subscription_tiers (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(40)  NOT NULL UNIQUE,        -- 'Free', 'Standard', 'Premium'
    description     TEXT,                                 -- short marketing blurb for the pricing page
    price           NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (price >= 0), -- major currency unit (e.g. 5000.00, not kobo)
    currency        VARCHAR(3)   NOT NULL DEFAULT 'NGN' CHECK (currency ~ '^[A-Z]{3}$'),
    "interval"      VARCHAR(10)  NOT NULL DEFAULT 'monthly' CHECK ("interval" IN ('monthly', 'yearly')),
    feature_list    JSONB        NOT NULL DEFAULT '[]',   -- ordered array of perk strings shown on the pricing page
    is_active       BOOLEAN      NOT NULL DEFAULT true,   -- false hides a retired tier from new customers
    display_order   INTEGER      NOT NULL DEFAULT 0,      -- ascending sort position on the pricing page
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (display_order)
);

CREATE INDEX IF NOT EXISTS idx_subscription_tiers_active_order
    ON subscription_tiers (is_active, display_order);

-- Seed the three tiers with fixed, predictable ids (1/2/3) so application
-- code can default new merchants to id 1 (Free) without a lookup.
-- ON CONFLICT keeps this script safe to re-run against an existing DB.
INSERT INTO subscription_tiers (id, name, description, price, currency, "interval", feature_list, is_active, display_order)
VALUES
  (1, 'Free', 'Get started with zero-signup ledger tracking on WhatsApp.',
     0.00, 'NGN', 'monthly',
     '["Unlimited sales, expense & debt logging via chat","Auto-generated receipt cards","Live BALANCE snapshot on demand","Daily Sunset Report on request"]'::jsonb,
     true, 1),
  (2, 'Standard', 'For growing merchants who want daily visibility and repeat-customer tracking.',
     5000.00, 'NGN', 'monthly',
     '["Everything in Free","Automatic Daily Sunset Report every evening","Monthly Insights summary","Smart Customer Loyalty Flags (5th-purchase pings)","Priority WhatsApp support"]'::jsonb,
     true, 2),
  (3, 'Premium', 'The full Kika AI experience: rich analytics and automated monthly reporting.',
     10000.00, 'NGN', 'monthly',
     '["Everything in Standard","Monthly Digest card with AI-generated insights","Full Monthly Report (weekly revenue, debtor breakdown, top products)","Smart Customer Loyalty Flags","Priority WhatsApp support"]'::jsonb,
     true, 3)
ON CONFLICT (id) DO NOTHING;

-- Keep the identity sequence ahead of the manually-seeded ids above, so
-- the next tier created through the app gets id 4, not a collision with 1-3.
SELECT setval(pg_get_serial_sequence('subscription_tiers', 'id'), 3, true);

DROP TRIGGER IF EXISTS trg_subscription_tiers_updated_at ON subscription_tiers;
CREATE TRIGGER trg_subscription_tiers_updated_at
    BEFORE UPDATE ON subscription_tiers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS merchants (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    whatsapp_number     VARCHAR(20)  NOT NULL UNIQUE,   -- E.164, e.g. +2348012345678
    display_name        VARCHAR(120),
    business_name       VARCHAR(160),
    subscription_tier_id INTEGER NOT NULL DEFAULT 1 REFERENCES subscription_tiers(id), -- 1 = Free
    subscription_expires_at TIMESTAMPTZ,                -- NULL while on the Free tier
    onboarding_state    VARCHAR(24)  NOT NULL DEFAULT 'PENDING_CONSENT'
                         CHECK (onboarding_state IN (
                            'PENDING_CONSENT', 'CONSENT_DECLINED', 'AWAITING_BUSINESS_NAME', 'NEW', 'ACTIVE',
                            'STANDARD_ACTIVE', 'PREMIUM_ACTIVE'
                         )),
    consent_at          TIMESTAMPTZ,                     -- when the merchant tapped "I AGREE" — compliance record
    consent_prompt_count SMALLINT NOT NULL DEFAULT 0,     -- how many times we've (re)sent the consent prompt without an accept; capped at 3 before we stop nudging
    closing_hour_local  SMALLINT NOT NULL DEFAULT 19 CHECK (closing_hour_local BETWEEN 0 AND 23), -- Africa/Lagos hour the Business Sunset ping fires
    logo_file_path       TEXT,                            -- uploaded business logo, embedded into receipts once set
    awaiting_logo_until TIMESTAMPTZ,                      -- short window after a fresh premium purchase where the next image is treated as a logo upload, not a transaction scan
    default_currency    VARCHAR(3)   NOT NULL DEFAULT 'NGN',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_merchants_whatsapp_number ON merchants (whatsapp_number);
CREATE INDEX IF NOT EXISTS idx_merchants_subscription_tier ON merchants (subscription_tier_id);
CREATE INDEX IF NOT EXISTS idx_merchants_closing_hour ON merchants (closing_hour_local);

-- Every sale / expense / debt entry a merchant records via chat.
-- `total_kobo` is the full value of the transaction; `paid_kobo` is what was
-- actually handed over at the time; `balance_kobo` is what's still owed
-- (0 for a fully-paid CREDIT/DEBIT). This three-way split mirrors how
-- merchants actually talk: "she pay 15k remain 12k" on a 27k sale.
CREATE TABLE IF NOT EXISTS ledger_entries (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    entry_type          VARCHAR(20) NOT NULL CHECK (entry_type IN ('CREDIT', 'DEBIT', 'DEBT', 'DEBT_SETTLEMENT')),
    counterparty_name   VARCHAR(160),                    -- customer/supplier name, optional
    counterparty_phone  VARCHAR(20),                     -- optional E.164 customer number, for loyalty tracking
    description         TEXT NOT NULL,
    items               JSONB NOT NULL DEFAULT '[]',     -- [{name, quantity, unit}], best-effort extraction
    total_kobo          BIGINT NOT NULL CHECK (total_kobo >= 0),
    paid_kobo           BIGINT NOT NULL DEFAULT 0 CHECK (paid_kobo >= 0),
    balance_kobo        BIGINT NOT NULL DEFAULT 0 CHECK (balance_kobo >= 0),
    balance_after_kobo  BIGINT,                          -- customer's rolling debt balance snapshot immediately after this entry (DEBT/DEBT_SETTLEMENT only) — computed under row lock, see customer_balances
    currency            VARCHAR(3) NOT NULL DEFAULT 'NGN',
    is_settled          BOOLEAN NOT NULL DEFAULT false,  -- true once balance_kobo hits 0
    is_voided           BOOLEAN NOT NULL DEFAULT false,  -- true once undone via the UNDO command
    voided_at           TIMESTAMPTZ,
    raw_message         TEXT,                            -- original WhatsApp text, for audit
    receipt_id          UUID,                             -- set once a receipt card is generated
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_merchant_created
    ON ledger_entries (merchant_id, created_at DESC) WHERE is_voided = false;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_outstanding_debt
    ON ledger_entries (merchant_id, is_settled) WHERE balance_kobo > 0 AND is_voided = false;
CREATE INDEX IF NOT EXISTS idx_ledger_entries_items_gin
    ON ledger_entries USING GIN (items);
CREATE INDEX IF NOT EXISTS idx_ledger_entries_counterparty_phone
    ON ledger_entries (merchant_id, counterparty_phone) WHERE counterparty_phone IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Customer balances — the single authoritative "account" row per
-- (merchant, customer) holding their current rolling debt balance.
--
-- This exists specifically to eliminate a race condition: ledger_entries
-- rows are independent inserts, so two "sales on credit" to the SAME
-- customer arriving within seconds of each other (two concurrent worker
-- jobs) have nothing to serialize against one another on if the rolling
-- total is only ever computed by SUMming ledger_entries at read time.
-- Every debt-affecting write (a new DEBT, or a DEBT_SETTLEMENT payment)
-- must go through queries.lockCustomerBalance() first, which:
--   1. INSERTs the row if it doesn't exist yet (ON CONFLICT DO NOTHING —
--      itself race-safe: if two transactions both try to create a brand
--      new customer's first row concurrently, only one insert wins)
--   2. SELECTs it back with FOR UPDATE inside the caller's transaction
-- A second concurrent transaction touching the same customer blocks on
-- that FOR UPDATE until the first COMMITs, then reads the up-to-date
-- balance — guaranteeing no lost updates regardless of how many sales
-- land for the same customer at the same instant.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_balances (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id          UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    counterparty_name    VARCHAR(160) NOT NULL,
    rolling_balance_kobo BIGINT NOT NULL DEFAULT 0 CHECK (rolling_balance_kobo >= 0),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, counterparty_name)
);

CREATE INDEX IF NOT EXISTS idx_customer_balances_merchant
    ON customer_balances (merchant_id);

DROP TRIGGER IF EXISTS trg_customer_balances_updated_at ON customer_balances;
CREATE TRIGGER trg_customer_balances_updated_at
    BEFORE UPDATE ON customer_balances
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Products / inventory — opt-in stock tracking. A product only exists
-- here once a merchant explicitly registers it via "ADD STOCK: name, qty".
-- Sales that mention a matching item name (case-insensitive) decrement
-- current_stock; crossing below low_stock_threshold fires the Low Stock
-- Alert appended to that sale's receipt.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id          UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    name                 VARCHAR(160) NOT NULL,
    unit                 VARCHAR(40),
    current_stock        NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    low_stock_threshold  NUMERIC(12, 2) NOT NULL DEFAULT 5,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness ("Rice" and "rice" are the same product)
-- via an expression index rather than a plain UNIQUE constraint.
CREATE UNIQUE INDEX IF NOT EXISTS idx_products_merchant_name_ci
    ON products (merchant_id, lower(name));

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Data exports — CSV ledger exports generated for premium merchants,
-- served the same way as receipts (unguessable token, expiring), and
-- swept by the same disk-cleanup job once expired.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS data_exports (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id     UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    file_path       TEXT NOT NULL,
    public_token    VARCHAR(64) NOT NULL UNIQUE,
    period_label    VARCHAR(40),
    expires_at      TIMESTAMPTZ NOT NULL,
    file_deleted_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_data_exports_public_token ON data_exports (public_token);
CREATE INDEX IF NOT EXISTS idx_data_exports_cleanup_sweep
    ON data_exports (expires_at) WHERE file_deleted_at IS NULL;

-- Tracks which merchants have already received a given day's Sunset
-- Report or a given month's Insights report, so a retried/duplicated
-- scheduler tick can never send the same report twice.
CREATE TABLE IF NOT EXISTS report_dispatch_log (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    report_type         VARCHAR(20) NOT NULL CHECK (report_type IN ('DAILY_SUNSET', 'MONTHLY_INSIGHTS', 'MONTHLY_DIGEST', 'FRIDAY_AMNESTY_PROMPT')),
    period_key          VARCHAR(10) NOT NULL,             -- 'YYYY-MM-DD' or 'YYYY-MM'
    sent_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, report_type, period_key)
);

-- Generated receipt card assets (rendered PNGs served over a signed URL).
CREATE TABLE IF NOT EXISTS receipts (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    ledger_entry_id      UUID REFERENCES ledger_entries(id) ON DELETE SET NULL,
    file_path           TEXT NOT NULL,
    public_token        VARCHAR(64) NOT NULL UNIQUE,   -- random, unguessable path segment
    expires_at          TIMESTAMPTZ NOT NULL,
    file_deleted_at     TIMESTAMPTZ,                    -- set once the on-disk file has been pruned (after expires_at); NULL while the file still exists
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_receipts_public_token ON receipts (public_token);
CREATE INDEX IF NOT EXISTS idx_receipts_cleanup_sweep
    ON receipts (expires_at) WHERE file_deleted_at IS NULL;

-- Generated Monthly Digest card images (the compact WhatsApp visual with
-- Money Inflow / Outstanding Credit / Trade Days / Top Debtor).
CREATE TABLE IF NOT EXISTS digest_cards (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    period_key          VARCHAR(10) NOT NULL,            -- 'YYYY-MM'
    file_path           TEXT NOT NULL,
    public_token        VARCHAR(64) NOT NULL UNIQUE,
    expires_at          TIMESTAMPTZ NOT NULL,
    file_deleted_at     TIMESTAMPTZ,                      -- set once the on-disk file has been pruned (after expires_at); NULL while the file still exists
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, period_key)
);

CREATE INDEX IF NOT EXISTS idx_digest_cards_public_token ON digest_cards (public_token);
CREATE INDEX IF NOT EXISTS idx_digest_cards_cleanup_sweep
    ON digest_cards (expires_at) WHERE file_deleted_at IS NULL;

-- The full "View Full Report" web page a merchant lands on after tapping
-- through from their Monthly Digest — stored as a data snapshot (not
-- recomputed live) so the report stays consistent even as new ledger
-- entries come in after the digest was sent.
CREATE TABLE IF NOT EXISTS monthly_reports (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    period_key          VARCHAR(10) NOT NULL,            -- 'YYYY-MM'
    report_data         JSONB NOT NULL,                  -- full computed snapshot (totals, weekly revenue, debts, top products, AI insight)
    public_token        VARCHAR(64) NOT NULL UNIQUE,
    expires_at          TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, period_key)
);

CREATE INDEX IF NOT EXISTS idx_monthly_reports_public_token ON monthly_reports (public_token);

-- Loyalty tracking: one row per (merchant, customer phone). Purchases
-- increment purchase_count; every 5th purchase ("milestone") triggers a
-- ping to the customer, gated to Standard/Premium merchants only.
CREATE TABLE IF NOT EXISTS customer_loyalty (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    counterparty_phone  VARCHAR(20) NOT NULL,
    counterparty_name   VARCHAR(160),
    purchase_count      INTEGER NOT NULL DEFAULT 0,
    last_milestone_notified INTEGER NOT NULL DEFAULT 0,  -- last purchase_count a milestone ping was sent at
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, counterparty_phone)
);

-- Paystack payment attempts for tier upgrades.
CREATE TABLE IF NOT EXISTS payment_transactions (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    paystack_reference  VARCHAR(100) NOT NULL UNIQUE,
    subscription_tier_id INTEGER NOT NULL REFERENCES subscription_tiers(id),
    amount_kobo         BIGINT NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'ABANDONED')),
    authorization_url   TEXT,
    verified_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_reference
    ON payment_transactions (paystack_reference);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_merchant
    ON payment_transactions (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_tier
    ON payment_transactions (subscription_tier_id);

-- ---------------------------------------------------------------------------
-- Access control — blacklist/whitelist by WhatsApp number, and a
-- label-based bot pause so a human agent can take over a conversation
-- without the bot auto-replying underneath them.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS access_control_list (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number    VARCHAR(20) NOT NULL UNIQUE,          -- E.164
    list_type       VARCHAR(10) NOT NULL CHECK (list_type IN ('BLACKLIST', 'WHITELIST')),
    reason          TEXT,
    created_by      VARCHAR(120),                          -- admin identifier who added the rule
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_access_control_phone ON access_control_list (phone_number);
CREATE INDEX IF NOT EXISTS idx_access_control_type ON access_control_list (list_type);

-- Labels applied to a merchant's conversation (e.g. by a support agent in
-- a CRM/handoff tool). While an unresolved "skip" label is active
-- (matched against SKIP_BOT_LABELS), the bot logs the inbound message but
-- does not auto-reply, leaving the human agent in control.
CREATE TABLE IF NOT EXISTS conversation_labels (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id     UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    label           VARCHAR(60) NOT NULL,
    applied_by      VARCHAR(120),
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at      TIMESTAMPTZ                             -- NULL while still active
);

CREATE INDEX IF NOT EXISTS idx_conversation_labels_active
    ON conversation_labels (merchant_id) WHERE removed_at IS NULL;

-- ---------------------------------------------------------------------------
-- Payment links — every digital invoice/checkout link sent inside a
-- WhatsApp chat, across any gateway. `short_url` is the compact link
-- actually texted to the customer (see linkShortenerService); `gateway`
-- and `gateway_reference` tie it back to the underlying Paystack/Stripe/
-- Flutterwave transaction for reconciliation.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_links (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    gateway             VARCHAR(20) NOT NULL CHECK (gateway IN ('paystack', 'stripe', 'flutterwave')),
    gateway_reference   VARCHAR(150) NOT NULL,             -- the gateway's own transaction reference
    full_url            TEXT NOT NULL,                      -- the long authorization/checkout URL from the gateway
    short_url           VARCHAR(255) NOT NULL UNIQUE,       -- compact link sent in the WhatsApp text
    short_code          VARCHAR(20) NOT NULL UNIQUE,        -- the path segment of short_url, for fast lookup
    amount_kobo         BIGINT NOT NULL CHECK (amount_kobo >= 0),
    currency            VARCHAR(3) NOT NULL DEFAULT 'NGN',
    customer_phone      VARCHAR(20),
    customer_name       VARCHAR(160),
    description         TEXT,
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'EXPIRED', 'CANCELLED')),
    ledger_entry_id     UUID REFERENCES ledger_entries(id) ON DELETE SET NULL, -- set once payment auto-records a CREDIT
    expires_at          TIMESTAMPTZ NOT NULL,                -- when the link becomes invalid
    paid_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payment_links_short_code ON payment_links (short_code);
CREATE INDEX IF NOT EXISTS idx_payment_links_merchant ON payment_links (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_links_gateway_reference ON payment_links (gateway, gateway_reference);
CREATE INDEX IF NOT EXISTS idx_payment_links_status ON payment_links (status) WHERE status = 'PENDING';

DROP TRIGGER IF EXISTS trg_payment_links_updated_at ON payment_links;
CREATE TRIGGER trg_payment_links_updated_at
    BEFORE UPDATE ON payment_links
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Payment gateway activity log — every outbound call and inbound webhook
-- to/from any payment gateway (Paystack today), for reconciliation and
-- support debugging. Distinct from payment_transactions/payment_links,
-- which hold current state; this table is an append-only trail of every
-- attempt, retry, and webhook delivery.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_gateway_logs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID REFERENCES merchants(id) ON DELETE SET NULL,
    payment_link_id     UUID REFERENCES payment_links(id) ON DELETE SET NULL,
    gateway             VARCHAR(20) NOT NULL,
    event_type          VARCHAR(50) NOT NULL,   -- e.g. 'transaction.initialize', 'charge.success', 'verify.transaction'
    reference           VARCHAR(150),
    http_status         INTEGER,
    request_payload     JSONB,
    response_payload    JSONB,
    is_success          BOOLEAN NOT NULL,
    error_message       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payment_gateway_logs_reference ON payment_gateway_logs (reference);
CREATE INDEX IF NOT EXISTS idx_payment_gateway_logs_merchant ON payment_gateway_logs (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_gateway_logs_event ON payment_gateway_logs (gateway, event_type);

-- ---------------------------------------------------------------------------
-- Ledger disputes & adjustments — customer or merchant complaints about
-- an incorrect ledger balance, and how they were resolved.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ledger_disputes (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id         UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    ledger_entry_id     UUID REFERENCES ledger_entries(id) ON DELETE SET NULL,
    raised_by           VARCHAR(20) NOT NULL DEFAULT 'MERCHANT' CHECK (raised_by IN ('MERCHANT', 'CUSTOMER', 'SYSTEM')),
    customer_phone      VARCHAR(20),
    reason              TEXT NOT NULL,
    disputed_amount_kobo BIGINT,
    adjustment_amount_kobo BIGINT,          -- signed delta actually applied, once resolved
    status              VARCHAR(16) NOT NULL DEFAULT 'OPEN'
                         CHECK (status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED')),
    resolution_notes    TEXT,
    resolved_by         VARCHAR(120),
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_disputes_merchant ON ledger_disputes (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_disputes_status ON ledger_disputes (status) WHERE status IN ('OPEN', 'UNDER_REVIEW');

DROP TRIGGER IF EXISTS trg_ledger_disputes_updated_at ON ledger_disputes;
CREATE TRIGGER trg_ledger_disputes_updated_at
    BEFORE UPDATE ON ledger_disputes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Application/API audit log — every inbound HTTP request the service
-- handles (endpoint, method, status, actor), for security review and
-- operational debugging. Written by the auditLogger middleware on every
-- request; also used for explicit business-event audit entries (e.g.
-- "merchant.blacklisted", "payment_link.created") via auditLogService.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id     UUID REFERENCES merchants(id) ON DELETE SET NULL,
    actor_type      VARCHAR(20) NOT NULL DEFAULT 'SYSTEM' CHECK (actor_type IN ('MERCHANT', 'SYSTEM', 'ADMIN', 'WEBHOOK')),
    actor_id        VARCHAR(120),                -- phone number, admin username, or 'system'
    action          VARCHAR(100) NOT NULL,       -- e.g. 'ledger_entry.create', 'payment_link.create', 'merchant.blacklist'
    endpoint        VARCHAR(150),
    http_method     VARCHAR(10),
    status_code     INTEGER,
    is_success      BOOLEAN NOT NULL DEFAULT true,
    request_id      VARCHAR(64),
    ip_address      VARCHAR(45),
    metadata        JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_merchant ON audit_logs (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at DESC);

-- Attach the updated_at trigger to the remaining tables that need it.
DROP TRIGGER IF EXISTS trg_merchants_updated_at ON merchants;
CREATE TRIGGER trg_merchants_updated_at
    BEFORE UPDATE ON merchants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_customer_loyalty_updated_at ON customer_loyalty;
CREATE TRIGGER trg_customer_loyalty_updated_at
    BEFORE UPDATE ON customer_loyalty
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
