-- ---------------------------------------------------------------------------
-- This file has been retired as the live schema source.
--
-- Kika's database schema is now managed as versioned, tracked migrations
-- in src/db/migrations/ (run via `npm run migrate`, i.e. src/db/migrate.js)
-- instead of one ever-growing file re-run in full on every deploy.
--
-- The full schema as it existed at the point of this change is preserved
-- as src/db/migrations/0001_baseline.sql — see src/db/migrations/README.md
-- for how to add a new migration.
--
-- This file is kept only so anyone who bookmarked/linked it lands
-- somewhere useful; it is never read by any code.
-- ---------------------------------------------------------------------------
